apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: web-deployment-tls
spec:
  secretName: web-deployment-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: web-deployment.com
  dnsNames:
    - web-deployment.com
    - www.web-deployment.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - web-deployment.com
          - www.web-deployment.com