apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/dirctory
    email: 'vedantdave77@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}                         #  route website to let's encrypt (just to varify certificate )
  