apiVersion: apps/v1
kind: Deployment 
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: redis 
  template:
    metadata:
      labels:
        component: redis
    spec:
      containers:
        - name: redis
          image: redis  #no need of our docker repo
          ports:
            - containerPort: 6379
          resources:                       #providing resource to remove warning for cluster size
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0."
