apiVersion: apps/v1
kind: Deployment 
metadata:
  name: worker-deployment
spec:
  replicas: 1                 # This is the scaling componenets which works on the request so, whenever request comes to us for hght load scaling this docker images gies better laod handling capacity
  selector:
    matchLabels:
      component: worker 
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker
          image: vedantdave77/docker-worker
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
          resources:                       #providing resource to remove warning for cluster size
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"


# Worker connected to REDIS 